-- Part D: SQL Queries and Reports
-- Below is 10 SQL queries for the Parika Ferry System. 

-- Category 1: Basic Queries (Filters & Comparison)
-- 1. Track the New Vessel
-- Description: We need to verify that the new vessel, MV Konawaruk 1899, has been added and check the status of all active boats.

SELECT vessel_id, vessel_name, passenger_capacity, status
FROM vessel
WHERE vessel_name LIKE '%Konawaruk%'
   OR status = 'active';

 
-- 2. Freight Vehicles
-- Description: This query helps the loading staff identify heavy vehicles (like Trucks and Canters) paying more than $5,000, so they can prioritize them for deck space.

SELECT ticket_id, vehicle_type, plate_number, vehicle_fare_amount
FROM vehicle
WHERE vehicle_fare_amount > 5000
  AND vehicle_type IN ('Truck', 'Canter');

 
-- Category 2: Joins (Inner, Left, Right)

-- 3. Passengers (Inner Join)
-- Description: This query generates a list of all passengers booked on a specific schedule (Schedule ID 1). It joins four tables to get the passenger's full name and ID number, which is required for safety regulations.

SELECT 
   p.first_name, 
   p.last_name, 
   pass.id_number, 
   t.status
FROM ticket t
JOIN booking b ON t.booking_id = b.booking_id
JOIN passenger pass ON b.person_id = pass.person_id
JOIN person p ON pass.person_id = p.person_id
WHERE b.schedule_id = 1;

 
-- 4. Crew Roster for a Trip (Three-way Join)
-- Description: This report shows exactly which crew members are working on a specific trip (Schedule ID 1) and what their role is (e.g. Captain, Engineer) for that journey.

SELECT 
   p.first_name, 
   p.last_name, 
   c.crew_rank, 
   ca.role_on_trip
FROM crew_assignment ca
JOIN crew c ON ca.crew_person_id = c.person_id
JOIN person p ON c.person_id = p.person_id
WHERE ca.schedule_id = 1;

 
-- Category 3: Aggregation & Group By

-- 5. Revenue Per Route
-- Description: This report calculates the total passenger revenue generated by each route. We use a LEFT JOIN on the vehicle table to ensure we include tickets even if they don't have a vehicle attached.

SELECT 
   r.route_id,
   t.terminal_name as 'Origin',
   COUNT(tk.ticket_id) as 'Tickets Sold',
   COALESCE(SUM(tk.passenger_fare_amount), 0) as 'Passenger Revenue',
   COALESCE(SUM(v.vehicle_fare_amount), 0) as 'Cargo Revenue',
   (COALESCE(SUM(tk.passenger_fare_amount), 0) + COALESCE(SUM(v.vehicle_fare_amount), 0)) as 'Total Revenue'
FROM ticket tk
JOIN booking b ON tk.booking_id = b.booking_id
JOIN schedule s ON b.schedule_id = s.schedule_id
JOIN route r ON s.route_id = r.route_id
JOIN terminal t ON r.origin_terminal_id = t.terminal_id
LEFT JOIN vehicle v ON tk.ticket_id = v.ticket_id
GROUP BY r.route_id, t.terminal_name;

 
-- 6. Vessel Use
-- Description: This counts how many trips each vessel has successfully completed. This helps management see which boats are being used the most.

SELECT 
   v.vessel_name, 
   COUNT(s.schedule_id) as 'Trips Completed'
FROM schedule s
JOIN vessel v ON s.vessel_id = v.vessel_id
WHERE s.status = 'completed'
GROUP BY v.vessel_name;

 
-- Category 4: Sorting, Ordering, and Limiting

-- 7. Recent Bookings
-- Description: This query shows the 10 most recent bookings entered into the system, useful for the ticket office to track real-time activity.

SELECT 
   b.booking_id, 
   p.last_name, 
   b.booking_datetime, 
   b.status
FROM booking b
JOIN person p ON b.person_id = p.person_id
ORDER BY b.booking_datetime DESC
LIMIT 10;

 
-- 8. Highest Paid Crew Members
-- Description: A simple HR report to find the top 5 highest-earning crew members.

SELECT 
   p.first_name, 
   p.last_name, 
   c.crew_rank, 
   c.salary
FROM crew c
JOIN person p ON c.person_id = p.person_id
ORDER BY c.salary DESC
LIMIT 5;

 
-- Category 5: Complex Reporting (Subqueries & Multi-Table)

-- 9. The "Ghost Vehicle" Audit (Data Integrity Check)
-- Description: This query checks for data consistency errors. It looks for any vehicles that are linked to a ticket that has already been cancelled. Ideally, this should return zero results.

SELECT 
   v.plate_number, 
   v.vehicle_type, 
   t.status as ticket_status
FROM vehicle v
JOIN ticket t ON v.ticket_id = t.ticket_id
WHERE t.status = 'cancelled';

 
-- 10. Find Schedules with Above-Average Revenue
-- Description: This uses a subquery to calculate the average revenue across all trips, and then lists the specific schedules that earned more than that average (identifying peak trips).

SELECT 
   b.schedule_id, 
   COALESCE(SUM(t.passenger_fare_amount), 0) as trip_revenue
FROM ticket t
JOIN booking b ON t.booking_id = b.booking_id
GROUP BY b.schedule_id
HAVING trip_revenue > (
   SELECT AVG(total_per_trip)
   FROM (
		SELECT COALESCE(SUM(t2.passenger_fare_amount), 0) as total_per_trip
      FROM ticket t2
      JOIN booking b2 ON t2.booking_id = b2.booking_id
      GROUP BY b2.schedule_id
   ) as subquery
);